### PR TITLE
Word sorting anagram solver

### PR DESCRIPTION
**Pull request by proglottis**
I suspect the map implementation in #3 could be faster than this. Using sort makes the implementation quite concise though 😄

### CODE REVIEW

**Comment by plutov** [comment]
Thanks. Your solution is faster and has less code lines, I like it.
Compare with #3 on my host:
```3: 7824 ns/op
4: 4869 ns/op```

**Comment by plutov** [comment]
@proglottis I pushed new tests to this example, please try again with new tests.

**Comment by proglottis** [comment]
Okay, updated with some tweaks

**Comment by plutov** [comment]
Please pull new master tests+dict and make proper fixes.

**Comment by plutov** [comment]
@proglottis please check new tests and fix your PR.

**Pull request closed without merging**
