### PR TITLE
Implement the anagram

### PR DESCRIPTION
**Pull request by ledongthuc**
Hi @plutov, I see your comment in Golang Vietnam's Slack. I don't have much experience in performance optimization. But let try.

### CODE REVIEW

**Comment by plutov** [comment]
@ledongthuc, thanks. Your implementation is good, it's faster than other solutions (and it doesn't use any libs). Let's wait some time, and if there are no other solutions I will merge this one.

**Comment by plutov** [comment]
@ledongthuc  I pushed new tests to this example, please try again with new tests.

**Comment by plutov** [comment]
Please pull new master tests+dict and make proper fixes.

**Comment by ledongthuc** [comment]
Hi @plutov, I updated the code adapt the new tests.

**Comment by plutov** [comment]
Thanks, now it looks fine, I'll merge it

**Comment by plutov** [comment]
@ledongthuc I found that PR #4 is x4 faster with some modifications

**Comment by ledongthuc** [comment]
Hey @plutov, Sorry for late reply. 😄 Have something busy with company's tasks.

Nice to check the PR #4, it's clear and faster than this one 👍 . When I check its source code, I see it doesn't handle some small case.

Could you append some following test cases into file `dictionary.txt` and recheck it.

```
Real funn
Cite not imports
```

**Comment by plutov** [comment]
I have merged your solution with small performance fixes!

**Pull request merged**
