### PR TITLE
Implement Missing func

### PR DESCRIPTION
**Pull request by saheienko**
```
$ go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/saheienko/practice-go/missingnumbers
BenchmarkMissing-4   	 2000000	       730 ns/op	      48 B/op	       3 allocs/op
PASS
ok  	github.com/saheienko/practice-go/missingnumbers	2.199s
```

### CODE REVIEW

**Comment by plutov** [comment]
Thank you, before merging this I want to implement this issue, so we can have multiple solutions per challenge https://github.com/plutov/practice-go/issues/44

**Comment by plutov** [comment]
Tests do not pass, please check with fresh master.

**Comment by saheienko** [comment]
Test checks order. Is it an error?

```
$ go test .       
--- FAIL: TestMissingFuzzy (0.01s)        
        missingnumbers_test.go:73: test 2: expected [1816 4970] was [4970 1816]      
        missingnumbers_test.go:73: test 3: expected [2735 4586] was [4586 2735]      
        missingnumbers_test.go:73: test 5: expected [205 9243] was [9243 205]        
        missingnumbers_test.go:73: test 6: expected [3267 9029] was [9029 3267]      
FAIL                                      
FAIL    github.com/saheienko/practice-go/missingnumbers 0.006s 
```

**Comment by shogg** [comment]
The newly added test expects the results in ascending order. The original tests behave the same way.
It's easy to fix in your code. I did it for myself to benchmark your solution.

**Pull request closed without merging**
