### PR TITLE
Update missingnumbers.go

### PR DESCRIPTION
**Pull request by gladkikhartem**
BenchmarkMissing-4   	 1000000	      1373 ns/op

### CODE REVIEW

**Comment by plutov** [comment]
Thanks, I want to test your PR with tests added in https://github.com/plutov/practice-go/pull/38

**Comment by gladkikhartem** [comment]
You could test them on your machine, just to make results more accurate. I have I5 and 1333 Mhz RAM
goos: linux
goarch: amd64
BenchmarkMissing-4            	 1000000	      1535 ns/op
BenchmarkMissingFuzzy_1e2-4   	 2000000	       624 ns/op
BenchmarkMissingFuzzy_1e3-4   	  500000	      3873 ns/op
BenchmarkMissingFuzzy_1e4-4   	   50000	     36932 ns/op
BenchmarkMissingFuzzy_1e5-4   	    5000	    441091 ns/op
BenchmarkMissingFuzzy_1e6-4   	     100	  10156059 ns/op

**Comment by shogg** [comment]
I closed #38 and reopened it as #39. Plutov asked me to split tests/benchmarks and my solution into two commits.

Will there be a page with results?

I tested @gladkikhartem, @johandalabacka, @saheienko and my results for myself. First two perform nearly linear in time. @johandalabacka needs a huge amount of memory but seems to be faster in the end. Saheienko and I do poorly compared.

$ go test -bench . -benchmem

# gladkikhartem
BenchmarkMissing-8               1000000              1757 ns/op             160 B/op          5 allocs/op
BenchmarkMissingFuzzy_1e2-8      2000000               899 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e3-8       300000              5162 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e4-8        30000             50343 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e5-8         3000            486725 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e6-8          200           7572230 ns/op              16 B/op          1 allocs/op

# johandalabacka
BenchmarkMissing-8                500000              3133 ns/op             192 B/op          6 allocs/op
BenchmarkMissingFuzzy_1e2-8      2000000               890 ns/op              32 B/op          2 allocs/op
BenchmarkMissingFuzzy_1e3-8       500000              3776 ns/op             144 B/op          2 allocs/op
BenchmarkMissingFuzzy_1e4-8        50000             34900 ns/op            1296 B/op          2 allocs/op
BenchmarkMissingFuzzy_1e5-8         5000            352948 ns/op           13584 B/op          2 allocs/op
BenchmarkMissingFuzzy_1e6-8          500           2563447 ns/op          131088 B/op          2 allocs/op

# saheienko
BenchmarkMissing-8               2000000               972 ns/op              48 B/op          3 allocs/op
BenchmarkMissingFuzzy_1e2-8      1000000              1125 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e3-8       200000              6251 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e4-8        20000             77161 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e5-8         1000           1383168 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e6-8           50          28863108 ns/op              16 B/op          1 allocs/op

# shogg
BenchmarkMissing-8               1000000              1219 ns/op              48 B/op          3 allocs/op
BenchmarkMissingFuzzy_1e2-8      1000000              1101 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e3-8       200000              6292 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e4-8        20000             77577 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e5-8         1000           1411614 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e6-8           50          24199934 ns/op              16 B/op          1 allocs/op

PS: the 1 allocs/op can be easily eliminated but it doesn't gain any performance win.

**Comment by plutov** [comment]
Thank you, before merging this I want to implement this issue, so we can have multiple solutions per challenge https://github.com/plutov/practice-go/issues/44

**Comment by plutov** [comment]
Merging this as fastest solution!

**Pull request merged**
