### PR TITLE
Tests refactored

### PR DESCRIPTION
**Pull request by MuxN4**
Removed run function, and added separate Shorten and Expand benchmarks

### CODE REVIEW

**Comment by plutov** [comment]
You have now 2 PRs open, which one is the latest?

**Comment by MuxN4** [comment]
This is the latest one.

**Comment by plutov** [comment]
Hey @MuxN4 I am not sure if this is a good fit honestly. A lot of complexity of URL shorteners is scalability and making sure the hashes are unique. And they are not usually done with 2 ways encode/decode but rather use a DB. The task of creating a hash is pretty straightforward and I don't see what could be an interesting potential solution there.

**Comment by MuxN4** [comment]
@plutov, Thanks for the feedback. I understand your concerns about scalability and hash uniqueness in URL shorteners. My approach was to explore a simpler solution to demonstrate the basic concept and provide a starting point for further enhancements. I agree that for a production-ready system, using a database to manage hashes and ensure uniqueness is crucial. Is there a specific solution or approach you had in mind that could address these concerns?

**Comment by plutov** [comment]
I think it's a great idea, but maybe the challenge could be to implement the API with some sort of storage as well. Something similar to this one - https://codingchallenges.substack.com/p/coding-challenge-12-build-your-own

**Comment by MuxN4** [comment]
I’ve made key updates based on your feedback, including adding a REST API for URL shortening and expansion, developing a flexible storage interface for future persistence, enhancing the hashing mechanism, and ensuring idempotency. However, there’s still room for improvement, such as implementing DELETE functionality, adding persistent storage (e.g., Redis or a database), handling collisions for shorter codes, and expanding automated tests.Your feedback on the current implementation would be greatly appreciated.

**Pull request closed without merging**
