### PR TITLE
Anagrams

### PR DESCRIPTION
**Pull request by kennygrant**

### CODE REVIEW

**Comment by plutov** [comment]
@kennygrant and you won again! This solution is good, also thanks for edits.

**Comment by kennygrant** [comment]
Thanks, these are fun, I love this idea. Please do post them to [golangnews.com](https://golangnews.com) as well (I've just posted your jaro distance one). I do really like that these are relatively simple, and only take a few minutes or at most an hour to complete, it means people can contribute even if they are busy. 

I think I'll leave the latest ones to give others a go. It would perhaps be nice if people could submit different solutions, so that you see a range of solutions to the problem - perhaps you could set a deadline and then review all submissions by that date. That's how the ruby quiz used to do this and it worked well. 

I think having the problems be algos or data structures is really fun and interesting, and teaches people about things which are actually useful - things like a merkle tree and hash table would be good too in future. So thanks and keep up the good work!

**Comment by plutov** [comment]
@kennygrant thanks for the slot. I am thinking to make it able to merge multiple solutions, but do not know how to make it beautiful and work inside 1 package with 1 test file. And yes, in future I want to push some algorithms, like binary search, different sorting functions, etc. And later this repo can become a nice collection.

**Comment by plutov** [comment]
@kennygrant I have updated dictionary.txt for Anagrams in master. And now tests don't pass
.

**Comment by kennygrant** [comment]
argh yes new test cases reveal a flaw I think, might be necc. to sort to handle different counts of letters in dictionary. I had fun though, happy to see others entering too, I had a jaro solution but held off :)

**Pull request merged**
