### PR TITLE
Added travis-ci.org support

### PR DESCRIPTION
**Pull request by zerkms**
What do you think about having all the submitted solutions automatically tested?

### CODE REVIEW

**Comment by plutov** [comment]
Cool, but also please add label to the README.md which shows that tests are passing

**Comment by zerkms** [comment]
But you still need to configure the travis builds under your account.

Here it runs for my fork: https://travis-ci.org/zerkms/practice-go

**Comment by plutov** [comment]
Yes, now I see it takes a lot of time to run all tests.

**Comment by zerkms** [comment]
The tests are instant, but travis is slightly slow on bootstrapping the environment

**Pull request merged**
